language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t alexhndly/udemy-react .

script:
  - docker run -e CI=true alexhndly/udemy-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app : "udemy-react"
  env: "udemyreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-201401184069"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

